version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: rubocop
    versions:
    - 1.12.0
    - 1.12.1
    - 1.9.0
    - 1.9.1
  - dependency-name: listen
    versions:
    - 3.5.0
  - dependency-name: rspec-rails
    versions:
    - 4.1.0
    - 5.0.0
  - dependency-name: rails
    versions:
    - 6.1.1
    - 6.1.2
    - 6.1.2.1
    - 6.1.3
  - dependency-name: faker
    versions:
    - 2.16.0
  - dependency-name: puma
    versions:
    - 5.2.0
    - 5.2.1
  - dependency-name: database_cleaner
    versions:
    - 2.0.0
  - dependency-name: capybara
    versions:
    - 3.35.1
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
