language: ruby
rvm:
- 2.3.0
env:
  matrix:
  - RAILS_ENV=test
  global:
    secure: DkBmI1oIr67ogC/k9ZtbJBHpuxavdBeGSea4DqxE+BschL18JiHsCBqLIZ8u+emmcp/uoqPx/LD8kEY2FiR2JcqTRgwfE9cQCJwiDSNsiBKMcv9evo1+s4dNcEEyMUSfUw5s8LXqSXHlBUJ9xry6+r7xZN8FE4F7CtbgOCMtRPufgnbnTt1vJHY8+d7zgeiG822y+j6y8+f04Z4/FU4SWWI5f87JuBMKsGyaCaKqEMwGZaBT3zVMehzoR4wdDIRmF1xvjOK7brCy2uYWNDAW2hrmrnp4UoACWi11GVoYgAuOS9KhjBWmBOjOafEZHSIXHuteVIHkxEgwmYAd7rtztmF44gtb6WylAD8IArPMyMeWJ3294SVKl9QRSh86tUNEHleiJnibNBm2i8dU2DlaGyZMu8xb98czud4ss05uHi8mcjSEjBzQ0njB6PyKi+OmpA+uiMtqgATDJJpxP3uhzoE68Q5qXZtBrpESAX4PLknuRobxAzrvpOqVYSLo9s1J+IQMkyEzmWA0Nw0s1JYn2W1FE2wHaLIG7VpDbRct8KB4WSIFViwgSTbuSZRY3guuUJW1YwlELTsqTzQfjZDXo+q15I9lbl++sImNN20I/j3kQSTAL3RUM5QRRr51tD7VvMXuyel+7BWXWud9hklN8PtSxrnYxABdg/pzJ+y8NvA=
before_script:
- npm install -g bower
- bower install
- bundle exec rake db:setup
script:
- bundle exec rake
deploy:
  provider: heroku
  api_key:
    secure: WKhwzIKMkAI+BfGkbbIZI9+3CWtzBTL32bDU33EGDcQVVWJH2VLZmbme9eFHpsJ07jDrBz91Iy42j6dIgMCF6JgLlKNC83AS8/AakH5Q0MsSJci9vdv1UYPZrlfqXdgO30vtP1DNOskDE+PTdsZuw/GsoEiYoxkCwU9FQOejGiw+fq1qYedZ83fkrse7QVmjAEpOyYbEOR8auxAjtVGjQay/LZVMSPQ1Bo3gS8HPkZY1NHmOTJfwjHP/rfMfY4O0xkIT1BRh5dndKe+4Ciih882qsbr/r2Qu60ilgfLZS8KeNu+BreU2+asLMAjYIe1wGmD1QsawFLSKREX5kXAKYfVDud5bl4HSsUCnzy3LxZl0dCr4YRe9gk+elSYCeC8xRfDNyR3z5wzoezafBKuyiY5ektLkFhM+updZY74hvST0pk61K01wZj6Yr9668ScDJDsjg5JDr1wTJdS92jdi5c8S8ZcQWHCQJfpGA3KAu9NTqyVjZ84GnIu6d2E4vK8PLDOtqG7kgBaEhyemFTkybGG8kdwSS5iNP2K9BI/2f+Xt29sTNJrlIa2k5UtdhE4n2E2hhrRZnMqw4EkTbjds7LqucuLmz7p64kZJHmTtAQ7ISBrr5xBMSF//SLNvzO1mE/Jwr1xJagvDZUgJKtF8Jkt5lio24XQzL7z3CpIqo8I=
  app: online-quizzes
