language: ruby
rvm:
- 2.3.0
env:
  matrix:
  - RAILS_ENV=test
  global:
    secure: DkBmI1oIr67ogC/k9ZtbJBHpuxavdBeGSea4DqxE+BschL18JiHsCBqLIZ8u+emmcp/uoqPx/LD8kEY2FiR2JcqTRgwfE9cQCJwiDSNsiBKMcv9evo1+s4dNcEEyMUSfUw5s8LXqSXHlBUJ9xry6+r7xZN8FE4F7CtbgOCMtRPufgnbnTt1vJHY8+d7zgeiG822y+j6y8+f04Z4/FU4SWWI5f87JuBMKsGyaCaKqEMwGZaBT3zVMehzoR4wdDIRmF1xvjOK7brCy2uYWNDAW2hrmrnp4UoACWi11GVoYgAuOS9KhjBWmBOjOafEZHSIXHuteVIHkxEgwmYAd7rtztmF44gtb6WylAD8IArPMyMeWJ3294SVKl9QRSh86tUNEHleiJnibNBm2i8dU2DlaGyZMu8xb98czud4ss05uHi8mcjSEjBzQ0njB6PyKi+OmpA+uiMtqgATDJJpxP3uhzoE68Q5qXZtBrpESAX4PLknuRobxAzrvpOqVYSLo9s1J+IQMkyEzmWA0Nw0s1JYn2W1FE2wHaLIG7VpDbRct8KB4WSIFViwgSTbuSZRY3guuUJW1YwlELTsqTzQfjZDXo+q15I9lbl++sImNN20I/j3kQSTAL3RUM5QRRr51tD7VvMXuyel+7BWXWud9hklN8PtSxrnYxABdg/pzJ+y8NvA=
before_script:
- npm install -g bower
- bower install
- bundle exec rake db:setup
script:
- bundle exec rake
deploy:
  provider: heroku
  api_key:
    secure: dfawduJommezzb+/6fG9cO5Js/x4mBTQjmcv44vdLnuQBg0I8aIqK5W7zs2D6C4bs2E/TM3sX1zYjstI1SF9pf263M4eFMV0842UpbeHowY619RKcj9helr7xnQ7sKzx2l26E68KVx0O16oZRUbk3FZ7qelRQ1BhUX7jmrzbBYr2ldbihKWPyJ9j4F430JCqlMoe7Jtp/T6ba628WV1xMKOFg5q9kn5XqrjH+ykwz5Q77E1lRjrHXVI7vjOUKWJFaEWOhS8vyH9qIf5TAVUcstfJ605SkgnEHUaUu0tubR3nNhHsSNxHDHWcAF+5z/anJ7TvKzvIKnhrgsRHTj4lSnfkOWfa+EZR6cH/QQrCLqbse5bllf7IvMpu7vu3DnFhZ+wCd7CIznyPzdDqZoIKy78gCA/C491Eh6KLbw+CgqmcEeh3HFricZ7umfRIJXspThY2RXdDVeYb5Aotoiag9cDB7qFWgK3dJFSRFhewi9PrvE8oBoR4xdW9jDsq2dgjUczMW41m/xycDTUs0RDynZraRImAeMsBwmRBehMOHycBSSYwBm3LGebJp5pPkeuIumgxd0lneFwLFzdvptzBN/xZ1RM9/7WQ0eOiiQQyKE6njkcBwnMpVgZpGTtlN8gPXIaqovd4Pk5QjDw+UCTMzPiVuT8k7DEyOtd+eEJW3ZQ=
  app: online-quizzes
